-- 코드를 입력하세요
SELECT
    II.FLAVOR
    FROM FIRST_HALF FH
    JOIN ICECREAM_INFO II
    ON FH.FLAVOR = II.FLAVOR
    WHERE II.INGREDIENT_TYPE='fruit_based'
    AND TOTAL_ORDER > 3000 
    ORDER BY TOTAL_ORDER DESC